# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches: 
      - master
  push: 
    branches:
      - master
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build and test
      uses: ashutoshvarma/action-cmake-build@master
      with: 
        build-dir: ${{ runner.workspace }}/build
        cc: clang
        cxx: clang++
        
     
